#!/bin/bash

set -euxo pipefail

if [ ! -d ./cmd/fleetcontroller ]; then
  echo "please change the current directory to the fleet repo checkout"
  exit 1
fi

upstream_ctx="${FLEET_E2E_CLUSTER-k3d-upstream}"

## The upstream cluster to import all the images to.
k3d image import rancher/fleet:attach -c "${upstream_ctx#k3d-}"
k3d image import rancher/fleet:debug -c "${upstream_ctx#k3d-}"
