#!/usr/bin/env bash

set -e

function k3d-cluster-delete {
    if [ -z "$1" ]; then
        return
    fi

    echo k3d cluster delete "$1"
    k3d cluster delete "$1"
}

if [[ -n "${FLEET_E2E_CLUSTER}" ]]; then
    k3d-cluster-delete "${FLEET_E2E_CLUSTER#k3d-}"
fi

if [[ -n "${FLEET_E2E_CLUSTER_DOWNSTREAM}" ]]; then
    k3d-cluster-delete "${FLEET_E2E_CLUSTER_DOWNSTREAM#k3d-}"
fi

if [[ -z "${FLEET_E2E_CLUSTER}" && -z "${FLEET_E2E_CLUSTER_DOWNSTREAM}" ]]; then
    >&2 echo "No cluster to delete, please load the environment variables from the appropriate cluster config file."
    return 1
fi

