#!/usr/bin/env bash

export DEFAULT_CONFIG="dev/env.multi-cluster-defaults"
export CUSTOM_CONFIG_FILE="env.multi-cluster"

# shellcheck source=dev/setup-cluster-config
source dev/setup-cluster-config

FLEET_E2E_DS_CLUSTER_COUNT=${FLEET_E2E_DS_CLUSTER_COUNT:-1}

function setup-rancher() {
    if [ -z "$public_hostname" ]; then
        public_hostname=$(
            kubectl get service -n kube-system traefik -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
        ).nip.io
        export public_hostname
    fi
    ./dev/setup-rancher-clusters
    ./dev/register-downstream-clusters "$public_hostname"
}

function clean() {
    # Cleans with settings sourced, so it should be rather selective.
    ./dev/k3d-clean
}

function setup() {
    ./dev/setup-k3ds
    ./dev/build-fleet
    ./dev/import-images-k3d
    ./dev/setup-fleet-multi-cluster
}

function infra() {
    # needed for gitrepo tests
    ./dev/import-images-tests-k3d
    ./dev/create-zot-certs 'FleetCI-RootCA' # for OCI tests
    ./e2e/testenv/infra/infra setup
}

function all() {
    clean
    setup
    infra
    setup-rancher
}

function all-rancher() {
    clean
    setup
    infra
    setup-rancher
}

if [ -z "$1" ]; then
    all
else
    "$@"
fi
