#!/bin/bash

set -euxo pipefail

args=${k3d_args-}
docker_mirror=${docker_mirror-}
name=${1-upstream} # TODO refactor to use FLEET_E2E_UPSTREAM for consistency with setup-k3ds
i=${2-0}

if [ -n "$docker_mirror" ]; then
  TMP_CONFIG="$(mktemp)"
  trap "rm -f $TMP_CONFIG" EXIT

  cat << EOF > "$TMP_CONFIG"
mirrors:
  "docker.io":
      endpoint:
            - $docker_mirror
EOF
  args="$args --registry-config $TMP_CONFIG"
fi

k3d cluster create "$name" --servers 3 --api-port $(( 36443 + i )) -p "$(( 8080 + i )):80@server:0" -p "$(( 8443 + i )):443@server:0" $args
