#!/usr/bin/env bash

export DEFAULT_CONFIG="dev/env.multi-cluster-defaults"
export CUSTOM_CONFIG_FILE="env.multi-cluster"

# shellcheck source=dev/setup-cluster-config
source dev/setup-cluster-config

# needed for gitrepo tests
./dev/import-images-tests-k3d
./dev/create-zot-certs 'FleetCI-RootCA' # for OCI tests
./e2e/testenv/infra/infra setup
