#!/usr/bin/env bash

export DEFAULT_CONFIG="dev/env.single-cluster-defaults"
export CUSTOM_CONFIG_FILE="env.single-cluster"

# shellcheck source=dev/setup-cluster-config
source ./dev/setup-cluster-config

# Cleans with settings sourced, so it should be rather selective.
./dev/k3d-act-clean

export args="--k3s-arg --flannel-backend=none@server:* --k3s-arg --disable-network-policy"
./dev/setup-k3d "${FLEET_E2E_CLUSTER#k3d-}" $(( RANDOM % 10001 ))
kubectl apply -f https://calico-v3-25.netlify.app/archive/v3.25/manifests/calico.yaml

exit 0

./dev/build-fleet
./dev/import-images-k3d
./dev/setup-fleet "${FLEET_E2E_CLUSTER#k3d-}" '[
    {
        "id": "shard0",
        "nodeSelector": {
            "kubernetes.io/hostname": "k3d-upstream-server-0"
        }
    },
    {
        "id": "shard1"
    },
    {
        "id": "shard2",
        "nodeSelector": {
            "kubernetes.io/hostname": "k3d-upstream-server-2"
        }
    }
]'

# needed for gitrepo tests
./dev/import-images-tests-k3d
./dev/create-zot-certs 'FleetCI-RootCA' # for OCI tests
./e2e/testenv/infra/infra setup
