apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
spec:
  selector:
    matchLabels:
      {{- range $key, $value := .MatchLabels}}
      {{$key}}: {{$value}}
      {{- end}}
