apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}
spec:
  selector:
    app: fleet-controller
    shard-default: "true"
  ports:
    - protocol: TCP
      port: {{ .Port }}
      targetPort: metrics
  type: LoadBalancer
