apiVersion: v1
kind: Service
metadata:
  name: fleet-controller-metrics
  labels:
    app: fleet-controller
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: fleet-controller-metrics
  selector:
    app: fleet-controller
