ARG BUILD_ENV=dapper
ARG ARCH

FROM --platform=linux/$ARCH registry.suse.com/bci/bci-base:15.7 AS base
RUN zypper rm -y container-suseconnect && \
    zypper ar --priority=500 https://download.opensuse.org/repositories/Virtualization:containers/5.5/Virtualization:containers.repo && \
    zypper --gpg-auto-import-keys ref && \
    zypper -n update && \
    zypper -n install --no-recommends openssh-clients tini git-core && \
    zypper -n clean -a && \
    rm -fr /var/log/zypp* /usr/share/doc

FROM base AS copy_dapper
ONBUILD ARG ARCH
ONBUILD COPY bin/fleetcontroller-linux-$ARCH /usr/bin/fleetcontroller
ONBUILD COPY bin/fleet-linux-$ARCH /usr/bin/fleet

FROM base AS copy_buildx
ONBUILD ARG TARGETARCH
ONBUILD COPY bin/fleetcontroller-linux-$TARGETARCH /usr/bin/fleetcontroller
ONBUILD COPY bin/fleet-linux-$TARGETARCH /usr/bin/fleet

FROM base AS copy_goreleaser
ONBUILD ARG ARCH
ONBUILD COPY fleetcontroller-linux-$ARCH /usr/bin/fleetcontroller
ONBUILD COPY fleet-linux-$ARCH /usr/bin/fleet

FROM copy_${BUILD_ENV}

# Install Go 1.25+ for DWARFv5 support in Delve
RUN curl -L https://go.dev/dl/go1.25.1.linux-amd64.tar.gz | tar -xz -C /usr/local && \
    mv /usr/local/go /usr/local/go1.25 && \
    ln -sf /usr/local/go1.25/bin/go /usr/local/bin/go && \
    ln -sf /usr/local/go1.25/bin/gofmt /usr/local/bin/gofmt

# Install dlv with Go 1.25+ to support DWARFv5
RUN GOBIN=/usr/local/bin go install github.com/go-delve/delve/cmd/dlv@latest

# Expose debugging port for Delve
EXPOSE 2345

ENTRYPOINT [ "tini", "--", "dlv", "--listen=0.0.0.0:2345", "--headless=true", "--api-version=2", "--accept-multiclient", "exec" ]

