ARG BUILD_ENV=dapper
ARG ARCH

FROM --platform=linux/$ARCH registry.suse.com/bci/bci-base:15.7 AS base
RUN zypper rm -y container-suseconnect && \
    zypper ar --priority=500 https://download.opensuse.org/repositories/Virtualization:containers/5.5/Virtualization:containers.repo && \
    zypper --gpg-auto-import-keys ref && \
    zypper -n update && \
    zypper -n install --no-recommends openssh-clients tini git-core && \
    zypper -n clean -a && \
    rm -fr /var/log/zypp* /usr/share/doc

ENV DEBUG_PORT=2345
ENV PID=7

# Install Go for delve
RUN curl -L https://go.dev/dl/go1.25.1.linux-amd64.tar.gz | tar -xz -C /usr/local

# Install dlv
RUN /usr/local/go/bin/go install github.com/go-delve/delve/cmd/dlv@latest

# Copy dlv to standard location
RUN cp /root/go/bin/dlv /usr/local/bin/

# Expose debugging port
EXPOSE 2345

# Keep container running and ready for debugging commands
ENTRYPOINT ["/bin/sh", "-c", "/usr/local/bin/dlv attach $PID --headless --listen=:$DEBUG_PORT --api-version=2 --accept-multiclient"]

